[phases.setup]
nixPkgs = ["go"]

[phases.build]
cmds = ["go mod download", "go build -o bin/app ."]

[phases.start]
cmds = ["go install github.com/gobuffalo/soda@latest && export PATH=$PATH:/root/go/bin && soda migrate up", "./bin/app"]
