[phases.setup]
nixPkgs = ["go"]

[phases.build]
cmds = ["export PATH=$PATH:/root/go/bin && go install github.com/gobuffalo/cli/cmd/buffalo@latest && go install github.com/gobuffalo/soda/v3/cmd/soda@latest && buffalo build -o bin/app"]

[phases.start]
cmds = ["export PATH=$PATH:/root/go/bin:/usr/local/go/bin && /root/go/bin/soda migrate up", "./bin/app"]
