[phases.setup]
nixPkgs = ["go"]

[phases.build]
cmds = ["export PATH=$PATH:/root/go/bin && go install github.com/gobuffalo/cli/cmd/buffalo@latest && buffalo build -o bin/app"]

[phases.start]
cmds = ["soda migrate up", "./bin/app"]
