[phases.setup]
nixPkgs = ["go"]

[phases.install]
cmds = ["go mod download"]

[phases.build]
cmds = ["go build -o app ./cmd/app", "chmod +x app"]

[start]
cmd = "go install github.com/gobuffalo/soda@latest && export PATH=$PATH:/root/go/bin && soda migrate up && ./app"
