[phases.setup]
nixPkgs = ["go"]

[phases.start]
cmds = ["go mod download", "go build -o bin/app ./cmd/app", "chmod +x bin/app", "go install github.com/gobuffalo/soda@latest && export PATH=$PATH:/root/go/bin && soda migrate up", "./bin/app"]
