// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Header() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<header class=\"avr-header\"><div class=\"header-grid\"><div class=\"header-left\"><img src=\"/assets/images/Armed-Services-Logos.avif\" alt=\"American Veterans Rebuilding\" class=\"armed-services-logo\"></div><div class=\"header-center\"><a href=\"/\"><img src=\"/assets/images/logo.avif\" alt=\"AVRNPO\" class=\"main-logo\"></a><p class=\"tagline\">Rebuilding the American Veteran's Self, Family and Community.</p></div><div class=\"header-right\"><a href=\"https://www.facebook.com/AmericanVeteransRebuilding\" target=\"_blank\" class=\"social-icon\"><img src=\"/assets/images/Facebook.svg\" alt=\"Facebook\"></a> <a href=\"https://x.com/avrnpo\" target=\"_blank\" class=\"social-icon\"><img src=\"/assets/images/X.svg\" alt=\"X\"></a> <a href=\"https://discord.com/invite/f6TzKart7J\" target=\"_blank\" class=\"social-icon\"><img src=\"/assets/images/Discord.svg\" alt=\"Discord\"></a> <a href=\"https://open.spotify.com/show/5BBarK2chVBVPCbqrILO73\" target=\"_blank\" class=\"social-icon\"><img src=\"/assets/images/Spotify.svg\" alt=\"Spotify\"></a></div></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func Navigation() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<nav class=\"avr-navigation sticky-header\" hx-trigger=\"intersect once from:.sticky-header-sentinel\" hx-get=\"/api/nav-state\" hx-swap=\"outerHTML\"><div class=\"nav-links\"><a href=\"/#mission\" role=\"button\" class=\"outline nav-link\" data-section=\"mission\">Mission</a> <a href=\"/#blog\" role=\"button\" class=\"outline nav-link\" data-section=\"blog\">Updates</a> <a href=\"/#team\" role=\"button\" class=\"outline nav-link\" data-section=\"team\">Team</a> <a href=\"/#projects\" role=\"button\" class=\"outline nav-link\" data-section=\"projects\">Projects</a> <a href=\"/#donate\" role=\"button\" class=\"outline nav-link\" data-section=\"donate\">Donate</a> <a href=\"/#contact\" role=\"button\" class=\"outline nav-link\" data-section=\"contact\">Contact</a></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func NavigationScrolled() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<nav class=\"avr-navigation sticky-header scrolled\"><div class=\"nav-links\"><a href=\"/#mission\" role=\"button\" class=\"outline nav-link\" data-section=\"mission\">Mission</a> <a href=\"/#blog\" role=\"button\" class=\"outline nav-link\" data-section=\"blog\">Updates</a> <a href=\"/#team\" role=\"button\" class=\"outline nav-link\" data-section=\"team\">Team</a> <a href=\"/#projects\" role=\"button\" class=\"outline nav-link\" data-section=\"projects\">Projects</a> <a href=\"/#donate\" role=\"button\" class=\"outline nav-link\" data-section=\"donate\">Donate</a> <a href=\"/#contact\" role=\"button\" class=\"outline nav-link\" data-section=\"contact\">Contact</a></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func Footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<footer class=\"container\"><hr><div class=\"grid\"><div><p><strong>American Veterans Rebuilding</strong></p><p>Supporting veterans in their journey home.</p><p><small>&copy; ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(templ.EscapeString(currentYear()))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/navigation.templ`, Line: 69, Col: 56}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, " American Veterans Rebuilding. All rights reserved.</small></p></div><div><p><strong>Quick Links</strong></p><ul><li><a href=\"/about\">About Us</a></li><li><a href=\"/blog\">Blog</a></li><li><a href=\"/donate\">Donate</a></li><li><a href=\"/contact\">Contact</a></li></ul></div><div><p><strong>Legal</strong></p><ul><li><a href=\"/privacy\">Privacy Policy</a></li><li><a href=\"/terms\">Terms of Service</a></li></ul><p><small>Tax ID: [EIN]</small></p></div></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
